import type { LegalDoc } from "../types";

export const privacy: LegalDoc = {
  slug: "privacy",
  title: "Privacy Policy",
  description:
    "How TokSol handles personal data on its informational website, including the browser-only contact form and hosting server logs.",
  lastUpdated: "10 July 2026",
  intro:
    "This Privacy Policy explains what limited personal data is involved when you use the TokSol website and how we handle it. TokSol builds tokenization technology for real-world assets, and this site exists only to describe that work. It has no accounts, no login and no backend that collects or stores what you type. We have designed the site to gather as little information as possible, and this policy sets out honestly what does and does not happen when you visit.",
  clauses: [
    {
      id: "scope",
      heading: "Scope of this policy",
      paragraphs: [
        "This policy covers personal data connected with your use of this website. It does not cover the separate, contractual handling of data that takes place inside a client engagement, which is governed by the relevant service agreement and data-processing terms.",
        "\"Personal data\" means information that identifies or relates to an identifiable individual, such as a name, email address or IP address.",
      ],
    },
    {
      id: "contact-form",
      heading: "The contact form runs entirely in your browser",
      paragraphs: [
        "Our contact form does not transmit anything to a TokSol server. It runs entirely in your browser and simply composes a pre-filled email using a mailto: link, which opens in your own email application.",
        "This means we receive your name, email address and message only if, and at the moment when, you choose to send that email yourself from your own mail client. Nothing you type is stored by, or even reaches, TokSol unless you deliberately send the email. If you close the tab before sending, we never see it.",
      ],
    },
    {
      id: "server-logs",
      heading: "Hosting server logs",
      paragraphs: [
        "Like almost all websites, the site is delivered by a hosting provider whose servers automatically record standard technical log data when a page is requested. This typically includes your IP address, the date and time, the pages or files requested, and your browser type and user-agent string.",
        "These logs are generated by the hosting infrastructure for security, abuse prevention, troubleshooting and reliable operation of the site. We do not use them to build profiles of visitors or to track you across other websites.",
      ],
    },
    {
      id: "no-analytics",
      heading: "No analytics or advertising trackers",
      paragraphs: [
        "By default this site loads no analytics, advertising, fingerprinting or social-media tracking scripts, and it sets no cookies of its own. We do not follow you around the web and we do not sell attention.",
        "The one third-party element is an embedded YouTube video, which only loads after you click to play it. See our Cookie Policy for details of what YouTube may then set.",
      ],
    },
    {
      id: "how-we-use",
      heading: "How we use information",
      paragraphs: [
        "If you email us, whether through the contact form or directly, we use your details solely to read and respond to your enquiry and to carry on any resulting business correspondence.",
        "We use hosting server logs only to keep the site secure, available and functioning correctly. We do not use any of this information for automated decision-making that produces legal or similarly significant effects.",
      ],
    },
    {
      id: "legal-bases",
      heading: "Legal bases for processing",
      paragraphs: [
        "Where the GDPR or a comparable regime applies, we rely on the following legal bases:",
      ],
      list: [
        "Legitimate interests, for keeping the site secure and operational through hosting logs, and for responding to unsolicited enquiries you send us.",
        "Consent, which you give by choosing to send us an email, and, separately, by clicking to play the embedded YouTube video.",
        "Performance of a contract or steps taken at your request prior to a contract, where our correspondence concerns a possible or existing engagement.",
        "Compliance with legal obligations, where we are required to retain or disclose information by law.",
      ],
    },
    {
      id: "no-sale-sharing",
      heading: "No sale or sharing of personal data",
      paragraphs: [
        "We do not sell, rent or trade your personal data, and we do not share it for anyone else's marketing. We disclose information only to the limited service providers described below, or where we are legally compelled to do so.",
      ],
    },
    {
      id: "sub-processors",
      heading: "Service providers and sub-processors",
      paragraphs: [
        "To run the site and communicate with you we rely on a small number of providers acting on our behalf or as independent controllers:",
      ],
      list: [
        "Our website hosting provider, which serves the site and maintains the technical server logs described above.",
        "Our email provider, which we use to receive and reply to the messages you choose to send us.",
      ],
    },
    {
      id: "international-transfers",
      heading: "International transfers",
      paragraphs: [
        "Our providers may process data in countries other than your own. Where personal data is transferred across borders, we rely on the providers' lawful transfer mechanisms, such as standard contractual clauses or an applicable adequacy decision, to protect it.",
      ],
    },
    {
      id: "retention",
      heading: "Data retention",
      paragraphs: [
        "Hosting server logs are retained only for as long as the hosting provider needs them for security and operations, after which they are rotated or deleted.",
        "Emails you send us are kept for as long as needed to handle your enquiry and any resulting relationship, and thereafter only as required to meet legal, accounting or record-keeping obligations, before being deleted.",
      ],
    },
    {
      id: "your-rights",
      heading: "Your rights",
      paragraphs: [
        "Depending on where you live, you may have rights over your personal data, including the rights to:",
      ],
      list: [
        "Access the personal data we hold about you.",
        "Have inaccurate data rectified.",
        "Have your data erased where there is no overriding reason to keep it.",
        "Receive your data in a portable format, where applicable.",
        "Object to, or ask us to restrict, certain processing.",
        "Withdraw any consent you gave, without affecting processing already carried out.",
        "Lodge a complaint with your local data-protection supervisory authority.",
      ],
    },
    {
      id: "children",
      heading: "Children's data",
      paragraphs: [
        "This site addresses a business and professional audience and is not directed at children. We do not knowingly collect personal data from children. If you believe a child has sent us personal data, please contact us so we can delete it.",
      ],
    },
    {
      id: "changes",
      heading: "Changes to this policy",
      paragraphs: [
        "We may update this Privacy Policy to reflect changes to the site or to legal requirements. The date at the top shows the latest revision, and material changes will be reflected here.",
      ],
    },
    {
      id: "contact",
      heading: "How to make a privacy request",
      paragraphs: [
        "To exercise any of your rights or to ask a question about this policy, email pablofelipe@me.com. We will respond within the time frame required by applicable law.",
      ],
    },
  ],
};
